"""Correctly redefine TemplateItem model

Revision ID: 02e24e0ffa8b
Revises: eec97fab4d6e
Create Date: 2025-10-16 16:17:12.790575

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql


# revision identifiers, used by Alembic.
revision = '02e24e0ffa8b'
down_revision = 'eec97fab4d6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('template_items')
    op.create_table('template_items',
        sa.Column('id', sa.Integer(), nullable=False, primary_key=True, autoincrement=True),
        sa.Column('template_id', sa.Integer(), nullable=False),
        sa.Column('section', sa.String(length=255), nullable=True),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('details', sa.Text(), nullable=True),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.Column('display_order', sa.Integer(), nullable=True),
        sa.Column('date_field_required', sa.Boolean(), nullable=True),
        sa.Column('numeric_field_required', sa.Boolean(), nullable=True),
        sa.Column('boolean_field_required', sa.Boolean(), nullable=True),
        sa.Column('text_field_required', sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(['template_id'], ['pretrip_templates.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('template_items')
    op.create_table('template_items',
        sa.Column('template_id', sa.Integer(), nullable=False),
        sa.Column('item_id', sa.Integer(), nullable=False),
        sa.Column('display_order', sa.Integer(), nullable=True),
        sa.Column('required_override', sa.Boolean(), nullable=True),
        sa.Column('input_type_override', sa.String(length=50), nullable=True),
        sa.ForeignKeyConstraint(['item_id'], ['pretrip_items.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['template_id'], ['pretrip_templates.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('template_id', 'item_id')
    )
    # ### end Alembic commands ###