"""Remove unique constraint from PretripTemplate name

Revision ID: 0fae9a708795
Revises: f05876d12c3e
Create Date: 2025-10-16 16:43:37.199011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fae9a708795'
down_revision = 'f05876d12c3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pretrip_inspections', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('pretrip_inspections_ibfk_3'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], referent_schema='pretrip_db', ondelete='RESTRICT')

    with op.batch_alter_table('pretrip_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('name'))
        batch_op.drop_constraint(batch_op.f('pretrip_templates_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], referent_schema='pretrip_db')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pretrip_templates', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('pretrip_templates_ibfk_1'), 'users', ['user_id'], ['id'])
        batch_op.create_index(batch_op.f('name'), ['name'], unique=True)

    with op.batch_alter_table('pretrip_inspections', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('pretrip_inspections_ibfk_3'), 'users', ['user_id'], ['id'], ondelete='RESTRICT')

    # ### end Alembic commands ###
