"""Autogenerate migration to sync DB with models

Revision ID: 17b06d048b4b
Revises: abb036fc3494
Create Date: 2025-08-14 11:41:03.398963

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '17b06d048b4b'
down_revision = 'abb036fc3494'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('visit_log_table') # Deferring deletion until live server is updated
    with op.batch_alter_table('company_analytics_table', schema=None) as batch_op:
        batch_op.alter_column('generated_records_allowed',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('speeding_trend_json',
               existing_type=mysql.JSON(),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('distance_trend_json',
               existing_type=mysql.JSON(),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('start_date'))

    with op.batch_alter_table('driver_analytics_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('std_filter_threshold', sa.Float(), nullable=True))
        batch_op.alter_column('current_week_percent_speeding',
               existing_type=mysql.FLOAT(),
               nullable=False)
        batch_op.alter_column('current_week_distance_driven',
               existing_type=mysql.FLOAT(),
               nullable=False)
        batch_op.alter_column('records_count',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('speeding_trend_json',
               existing_type=mysql.JSON(),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('distance_trend_json',
               existing_type=mysql.JSON(),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('driver_id'))
        batch_op.drop_column('std_filter_value')

    with op.batch_alter_table('speedGauge_data', schema=None) as batch_op:
        batch_op.alter_column('is_interpolated',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Integer(),
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('speedGauge_data', schema=None) as batch_op:
        batch_op.alter_column('is_interpolated',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))

    with op.batch_alter_table('driver_analytics_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('std_filter_value', mysql.FLOAT(), nullable=True))
        batch_op.create_index(batch_op.f('driver_id'), ['driver_id', 'start_date'], unique=True)
        batch_op.alter_column('distance_trend_json',
               existing_type=sa.Text(),
               type_=mysql.JSON(),
               existing_nullable=True)
        batch_op.alter_column('speeding_trend_json',
               existing_type=sa.Text(),
               type_=mysql.JSON(),
               existing_nullable=True)
        batch_op.alter_column('records_count',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('current_week_distance_driven',
               existing_type=mysql.FLOAT(),
               nullable=True)
        batch_op.alter_column('current_week_percent_speeding',
               existing_type=mysql.FLOAT(),
               nullable=True)
        batch_op.drop_column('std_filter_threshold')

    with op.batch_alter_table('company_analytics_table', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('start_date'), ['start_date', 'generated_records_allowed'], unique=True)
        batch_op.alter_column('distance_trend_json',
               existing_type=sa.Text(),
               type_=mysql.JSON(),
               existing_nullable=True)
        batch_op.alter_column('speeding_trend_json',
               existing_type=sa.Text(),
               type_=mysql.JSON(),
               existing_nullable=True)
        batch_op.alter_column('generated_records_allowed',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)

    op.create_table('visit_log_table',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('timestamp', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('ip_address', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=45), nullable=False),
    sa.Column('path', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=False),
    sa.Column('method', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10), nullable=False),
    sa.Column('user_agent', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('status_code', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('username', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
