"""Recognize existing users table

Revision ID: 2a509575209c
Revises: 6cb7a4bd97b3
Create Date: 2025-08-11 17:34:23.569733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a509575209c'
down_revision = '6cb7a4bd97b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
