"""Add is_deleted 
  column to PretripInspection model for soft delete

Revision ID: 4029fe4002ec
Revises: 661acf5ee5c8
Create Date: 2025-10-16 21:38:16.619588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4029fe4002ec'
down_revision = '661acf5ee5c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pretrip_inspections', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=False))
        batch_op.create_index(batch_op.f('ix_pretrip_inspections_is_deleted'), ['is_deleted'], unique=False)
        batch_op.drop_constraint(batch_op.f('pretrip_inspections_ibfk_3'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], referent_schema='pretrip_db', ondelete='RESTRICT')

    with op.batch_alter_table('pretrip_templates', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('pretrip_templates_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], referent_schema='pretrip_db')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pretrip_templates', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('pretrip_templates_ibfk_1'), 'users', ['user_id'], ['id'])

    with op.batch_alter_table('pretrip_inspections', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('pretrip_inspections_ibfk_3'), 'users', ['user_id'], ['id'], ondelete='RESTRICT')
        batch_op.drop_index(batch_op.f('ix_pretrip_inspections_is_deleted'))
        batch_op.drop_column('is_deleted')

    # ### end Alembic commands ###
