"""Initial pretrip inspection models and relationships

Revision ID: 446547bef9dd
Revises: 66f936a12d87
Create Date: 2025-10-16 19:37:31.519773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '446547bef9dd'
down_revision = '66f936a12d87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pretrip_inspections',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('equipment_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('inspection_datetime', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['template_id'], ['pretrip_templates.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['pretrip_db.users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pretrip_inspections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pretrip_inspections_equipment_id'), ['equipment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pretrip_inspections_inspection_datetime'), ['inspection_datetime'], unique=False)
        batch_op.create_index(batch_op.f('ix_pretrip_inspections_user_id'), ['user_id'], unique=False)

    op.create_table('pretrip_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('inspection_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('item_snapshot', sa.JSON(), nullable=False),
    sa.Column('boolean_value', sa.Boolean(), nullable=True),
    sa.Column('numeric_value', sa.String(length=50), nullable=True),
    sa.Column('date_value', sa.Date(), nullable=True),
    sa.Column('text_value', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('severity', sa.Enum('ok', 'defect', 'action_required', name='result_severity'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['inspection_id'], ['pretrip_inspections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['item_id'], ['template_items.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pretrip_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pretrip_results_inspection_id'), ['inspection_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pretrip_results_item_id'), ['item_id'], unique=False)

    op.create_table('pretrip_photos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('result_id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=255), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['result_id'], ['pretrip_results.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pretrip_templates', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('pretrip_templates_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], referent_schema='pretrip_db')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pretrip_templates', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('pretrip_templates_ibfk_1'), 'users', ['user_id'], ['id'])

    op.drop_table('pretrip_photos')
    with op.batch_alter_table('pretrip_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pretrip_results_item_id'))
        batch_op.drop_index(batch_op.f('ix_pretrip_results_inspection_id'))

    op.drop_table('pretrip_results')
    with op.batch_alter_table('pretrip_inspections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pretrip_inspections_user_id'))
        batch_op.drop_index(batch_op.f('ix_pretrip_inspections_inspection_datetime'))
        batch_op.drop_index(batch_op.f('ix_pretrip_inspections_equipment_id'))

    op.drop_table('pretrip_inspections')
    # ### end Alembic commands ###
