"""Update PretripInspection and PretripResult models for inspection logging

Revision ID: 66f936a12d87
Revises: 0fae9a708795
Create Date: 2025-10-16 17:11:09.088781

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '66f936a12d87'
down_revision = '0fae9a708795'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pretrip_inspections', schema=None) as batch_op:
        batch_op.alter_column('equipment_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.drop_constraint(batch_op.f('pretrip_inspections_ibfk_3'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], referent_schema='pretrip_db', ondelete='RESTRICT')

    with op.batch_alter_table('pretrip_results', schema=None) as batch_op:
        batch_op.alter_column('item_snapshot',
               existing_type=mysql.JSON(),
               nullable=False)
        batch_op.drop_constraint(batch_op.f('pretrip_results_ibfk_2'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'template_items', ['item_id'], ['id'], ondelete='RESTRICT')

    with op.batch_alter_table('pretrip_templates', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('pretrip_templates_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], referent_schema='pretrip_db')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pretrip_templates', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('pretrip_templates_ibfk_1'), 'users', ['user_id'], ['id'])

    with op.batch_alter_table('pretrip_results', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('pretrip_results_ibfk_2'), 'pretrip_items', ['item_id'], ['id'], ondelete='RESTRICT')
        batch_op.alter_column('item_snapshot',
               existing_type=mysql.JSON(),
               nullable=True)

    with op.batch_alter_table('pretrip_inspections', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('pretrip_inspections_ibfk_3'), 'users', ['user_id'], ['id'], ondelete='RESTRICT')
        batch_op.alter_column('equipment_id',
               existing_type=mysql.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
