"""Final schema sync.

Revision ID: 6cb7a4bd97b3
Revises: efcc6afb6fe1
Create Date: 2025-08-10 21:50:52.472207

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cb7a4bd97b3'
down_revision = 'efcc6afb6fe1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
