"""Implement production-ready 
     model enhancements

Revision ID: 980a98378e51
Revises: cffa1e889c58
Create Date: 2025-09-13 12:43:39.824601

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '980a98378e51'
down_revision = 'cffa1e889c58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pretrip_inspections', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('pretrip_inspections_ibfk_3'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], referent_schema='pretrip_db', ondelete='RESTRICT')

    with op.batch_alter_table('pretrip_results', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_snapshot', sa.JSON(), nullable=True))
        batch_op.alter_column('severity',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.Enum('ok', 'defect', 'action_required', name='result_severity'),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pretrip_results', schema=None) as batch_op:
        batch_op.alter_column('severity',
               existing_type=sa.Enum('ok', 'defect', 'action_required', name='result_severity'),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.drop_column('item_snapshot')

    with op.batch_alter_table('pretrip_inspections', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('pretrip_inspections_ibfk_3'), 'users', ['user_id'], ['id'], ondelete='RESTRICT')

    # ### end Alembic commands ###
