"""Add Blueprint and BlueprintItem models

Revision ID: bb15f325f0ab
Revises: 980a98378e51
Create Date: 2025-09-24 21:44:11.854019

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb15f325f0ab'
down_revision = '980a98378e51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pretrip_blueprints',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('equipment_type', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('pretrip_blueprints', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pretrip_blueprints_equipment_type'), ['equipment_type'], unique=False)

    op.create_table('pretrip_blueprint_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('blueprint_id', sa.Integer(), nullable=False),
    sa.Column('section', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('date_field_required', sa.Boolean(), nullable=True),
    sa.Column('numeric_field_required', sa.Boolean(), nullable=True),
    sa.Column('boolean_field_required', sa.Boolean(), nullable=True),
    sa.Column('text_field_required', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['blueprint_id'], ['pretrip_blueprints.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pretrip_inspections', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('pretrip_inspections_ibfk_3'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], referent_schema='pretrip_db', ondelete='RESTRICT')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pretrip_inspections', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('pretrip_inspections_ibfk_3'), 'users', ['user_id'], ['id'], ondelete='RESTRICT')

    op.drop_table('pretrip_blueprint_items')
    with op.batch_alter_table('pretrip_blueprints', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pretrip_blueprints_equipment_type'))

    op.drop_table('pretrip_blueprints')
    # ### end Alembic commands ###
