"""add pretrip models and update users model

Revision ID: cffa1e889c58
Revises: 17b06d048b4b
Create Date: 2025-09-12 12:28:37.554693

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cffa1e889c58'
down_revision = '17b06d048b4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pretrip_templates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('equipment_type', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('equipment',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('equipment_type', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('default_template_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['default_template_id'], ['pretrip_templates.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('pretrip_inspections',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('equipment_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('inspection_datetime', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['template_id'], ['pretrip_templates.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['pretrip_db.users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pretrip_inspections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pretrip_inspections_equipment_id'), ['equipment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pretrip_inspections_inspection_datetime'), ['inspection_datetime'], unique=False)
        batch_op.create_index(batch_op.f('ix_pretrip_inspections_user_id'), ['user_id'], unique=False)

    op.create_table('pretrip_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('equipment_id', sa.Integer(), nullable=True),
    sa.Column('section', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('date_field_required', sa.Boolean(), nullable=True),
    sa.Column('numeric_field_required', sa.Boolean(), nullable=True),
    sa.Column('boolean_field_required', sa.Boolean(), nullable=True),
    sa.Column('text_field_required', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pretrip_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('inspection_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('boolean_value', sa.Boolean(), nullable=True),
    sa.Column('numeric_value', sa.String(length=50), nullable=True),
    sa.Column('date_value', sa.Date(), nullable=True),
    sa.Column('text_value', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('severity', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['inspection_id'], ['pretrip_inspections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['item_id'], ['pretrip_items.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pretrip_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pretrip_results_inspection_id'), ['inspection_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pretrip_results_item_id'), ['item_id'], unique=False)

    op.create_table('template_items',
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('required_override', sa.Boolean(), nullable=True),
    sa.Column('input_type_override', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['pretrip_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_id'], ['pretrip_templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('template_id', 'item_id')
    )
    op.create_table('pretrip_photos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('result_id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=255), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['result_id'], ['pretrip_results.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('visit_log_table')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('visit_log_table',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('timestamp', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('ip_address', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=45), nullable=False),
    sa.Column('path', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=False),
    sa.Column('method', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10), nullable=False),
    sa.Column('user_agent', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('status_code', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('username', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('pretrip_photos')
    op.drop_table('template_items')
    with op.batch_alter_table('pretrip_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pretrip_results_item_id'))
        batch_op.drop_index(batch_op.f('ix_pretrip_results_inspection_id'))

    op.drop_table('pretrip_results')
    op.drop_table('pretrip_items')
    with op.batch_alter_table('pretrip_inspections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pretrip_inspections_user_id'))
        batch_op.drop_index(batch_op.f('ix_pretrip_inspections_inspection_datetime'))
        batch_op.drop_index(batch_op.f('ix_pretrip_inspections_equipment_id'))

    op.drop_table('pretrip_inspections')
    op.drop_table('equipment')
    op.drop_table('pretrip_templates')
    # ### end Alembic commands ###
