"""Sync database schema.

Revision ID: efcc6afb6fe1
Revises: 6089694f356d
Create Date: 2025-08-10 21:41:13.643793

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'efcc6afb6fe1'
down_revision = '6089694f356d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('driver_analytics_table', schema=None) as batch_op:
        batch_op.drop_column('current_week_percent_speeding')
        batch_op.drop_column('current_week_distance_driven')

    op.add_column('driver_analytics_table', sa.Column('current_week_percent_speeding', sa.Float(), nullable=False, server_default=sa.text('0')))
    op.add_column('driver_analytics_table', sa.Column('current_week_distance_driven', sa.Float(), nullable=False, server_default=sa.text('0')))

    with op.batch_alter_table('driver_analytics_table', schema=None) as batch_op:
        batch_op.alter_column('records_count',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('speeding_trend_json',
               existing_type=mysql.JSON(),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('distance_trend_json',
               existing_type=mysql.JSON(),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('start_date'))
        batch_op.drop_column('std_filter_value')

    with op.batch_alter_table('speedGauge_data', schema=None) as batch_op:
        batch_op.alter_column('is_interpolated',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Integer(),
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('speedGauge_data', schema=None) as batch_op:
        batch_op.alter_column('is_interpolated',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))

    with op.batch_alter_table('driver_analytics_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('std_filter_value', mysql.FLOAT(), nullable=True))
        batch_op.create_index(batch_op.f('start_date'), ['start_date', 'driver_id'], unique=True)
        batch_op.alter_column('distance_trend_json',
               existing_type=sa.Text(),
               type_=mysql.JSON(),
               existing_nullable=True)
        batch_op.alter_column('speeding_trend_json',
               existing_type=sa.Text(),
               type_=mysql.JSON(),
               existing_nullable=True)
        batch_op.alter_column('records_count',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('current_week_distance_driven',
               existing_type=mysql.FLOAT(),
               nullable=True)
        batch_op.alter_column('current_week_percent_speeding',
               existing_type=mysql.FLOAT(),
               nullable=True)

    # ### end Alembic commands ###
